### ISSUE TITLE
[Feature request] Option to disable CPU mining when running miner in a GPU rig

### ISSUE THREAD

**Issue by gokul57** [bogdanadnan/multiminer#8] opened 2019-01-17 05:15 UTC
Hi

Please add an option to disable mining with CPU while running the miner in a GPU rig.

**Comment by bogdanadnan** [comment] 2019-01-17 09:15
Can you please give more details/screenshot regarding what you are asking for? If you use --use-gpu flag, the miner will NOT mine using CPU. High cpu usage is because gpu mining requires some computation done by the cpu in order to prepare work for gpu processing. Higher hashrate means more load on cpu to do this step.
If this is what you are asking for, i'm in the process of optimizing cpu usage and hashrate for gpu mining but that will take a while to complete and is not a bug/feature.

**Comment by bogdanadnan** [comment] 2019-01-17 14:59
Ah, got it, you where refering to OpenCL for CPU. I'll add a fix to remove cpu devices from OpenCL list.

**Comment by gokul57** [comment] 2019-01-17 15:35
Yeah, that what I requested. Thanks

**Comment by bogdanadnan** [comment] 2019-01-18 14:01
I've got reports that CPU OpenCL is in some cases faster than normal cpu mining, so I decided to leave CPU devices in the list. As you said you can get the same behaviour as you requested by using multiple gpu ids feature implemented on beta (will move it in master today and release a new windows build for it). So closing this issue.

**Closed by bogdanadnan** 2019-01-18 14:01 UTC
